# Generated by Django 2.0.7 on 2018-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('servicio', models.CharField(max_length=100)),
                ('cuidad', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
