# Generated by Django 2.0.7 on 2018-07-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_datoscsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscsv',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
