# Generated by Django 2.0.7 on 2018-08-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20180801_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='numero',
        ),
    ]
