# Generated by Django 2.0.7 on 2018-08-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_remove_contrato_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datosCsv',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ciudad',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pago',
            field=models.IntegerField(default=0),
        ),
    ]
