# Generated by Django 2.0.7 on 2018-08-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20180820_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='servicios.Persona'),
        ),
    ]
